server:
    port: 8080

session:
    expiration:
        duration: 10080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/wallet
        username: wallet
        password: wallet
    flyway:
        enabled: true
        locations:
          - db.migration
